pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                sh 'echo "Checking out source code..."'
            }
        }

        stage('Check Docker Environment') {
            steps {
                sh '''
                echo "PATH=$PATH"
                which docker || true
                docker --version || true
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t cicd-demo:v1 .
                '''
            }
        }
    }
}
