pipeline {

    agent any

    stages {

        stage('Checkout Source') {
           steps {
              echo 'Checking out source code...'
              checkout scm

              sh '''
              echo "Current Directory:"
              pwd
 
              echo "Files in current directory:"
              ls -la

              echo "Project-08 contents:"
              ls -la Project-08-End-to-End-CI-CD
              '''
       }
    }
        stage('Check Docker Environment') {
           steps {
              sh '''
              echo "PATH=$PATH"
              export PATH=/usr/local/bin:$PATH
              which docker
              docker --version
              '''
  
            }
        }

     stage('Build Docker Image') {
        steps {
           dir('Project-08-End-to-End-CI-CD') {
               sh '''
               export PATH=/usr/local/bin:$PATH
               docker build -t cicd-demo:v1 .
               '''
           }
       }
     }

       stage('Verify Docker Image') {
          steps {
             dir('Project-08-End-to-End-CI-CD') {
                sh '''
                export PATH=/usr/local/bin:$PATH
                docker images | grep cicd-demo
                '''
             }
        }
     } 

       stage('Deploy to Kubernetes') {
    steps {
        dir('Project-08-End-to-End-CI-CD') {
            sh '''
            kubectl apply -f deployment.yaml
            kubectl apply -f service.yaml
            '''
        }
    }
}

       stage('Verify Deployment') {
          steps {
             dir('Project-08-End-to-End-CI-CD') {
                 sh '''
                 kubectl get deployments
                 kubectl get services
                 kubectl get pods
                 '''
           }
       }
  }


}
    post {
        always {
            echo 'Pipeline execution completed.'
        }

        success {
            echo 'Deployment Successful.'
        }

        failure {
            echo 'Deployment Failed.'
        }
    }
}
